version: '3.8'

services:
  sloflix-addon:
    container_name: sloflix-stremio-addon
    build: .
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
      # Privzeti SloFlix API. Spremenite le, če veste, da se je naslov spremenil.
      - SLOFLIX_API_URL=https://api.sloflix.com
